### ISSUE TITLE
escaped forward slashes?

### ISSUE THREAD

**Issue by davidszotten** [davidblewett/rure-python#20]
Hi,

when trying to use rure on https://github.com/ua-parser/uap-core, i came across this behaviour where rure isn't consistent with re. i'm not sure who's "right"

```
$ python
Python 3.7.3 (default, May  6 2019, 08:10:06)
[Clang 9.0.0 (clang-900.0.38)] on darwin
>>> import re, rure
>>> re.match('\/', '/')
<re.Match object; span=(0, 1), match='/'>
>>> rure.match('\/', '/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
[snip]
rure.exceptions.RegexSyntaxError: regex parse error:
    \/
    ^^
error: unrecognized escape sequence
```

**Comment by BurntSushi** [comment]
This isn't a behavior of the binding. This is a behavior of the underlying regex library. The regex library does not let you escape characters that don't need to be escaped. Forward slashes are not special characters in the regex language.

More generally, there is no intent for rure to be drop in compatible with any other regex engine. There are a number of differences between them beyond escaping.

**Comment by davidszotten** [comment]
Thanks for the quick reply. So i guess the python implementation is just more lenient, and i guess uap escapes slashes in case they're used by eg a javascript engine?

**Comment by BurntSushi** [comment]
I'm on vacation, so I don't know off hand with certainty, but I don't think `/` is a special character in JavaScript regexes. It is special in regex _literals_ of course, but I don't think it is when using `new RegExp`. 

So I don't know why they escape them. You'd have to ask them. They probably needlessly escape other things too.

**Comment by davidblewett** [comment]
> More generally, there is no intent for rure to be drop in compatible with any other regex engine. There are a number of differences between them beyond escaping.

The Python wrapper does take some attempts to be as drop-in as possible. This package provides a compatibility layer to translate the Python standard library method signatures and flags to those used by `regex`. However, it does not try to work around more fundamental differences like this escaping issue, or arbitrary look around expressions for instance.

This package will always be more strict than the standard library when parsing input expressions.

**Comment by davidblewett** [comment]
I left a note about this in the readme ( https://github.com/davidblewett/rure-python/commit/ea26d711ff5724c605443147209475823208b8fd ).

@davidszotten if you would like further explanation in the readme, let me know.
